name: ImgMap
version: 2
main: com.tenko.ImgMap

commands:
    map:
        description: Renders an image.
        usage: /map <url>
        permission: imgmap.cmd.map
    smap:
        description: Renders a slideshow.
        usage: /smap <time> <url1> [url2] [url3]
        permission: imgmap.cmd.slideshow
    rmap:
        description: Restores a map.
        usage: /rmap
        aliases: restoremap
        permission: imgmap.cmd.restoremap
    imap:
        description: Gets the current version.
        usage: /imap
        aliases: imgmap
        permission: imgmap.cmd.imgmap

permissions:
    imgmap.*:
        description: Gives complete access to everything.
        children:
            imgmap.cmd.map: true
            imgmap.cmd.slideshow: true
            imgmap.cmd.restoremap: true
            imgmap.cmd.imgmap: true
        default: false
    imgmap.cmd.map:
        description: Allows the rendering of a single image.
        default: false
    imgmap.cmd.slideshow:
        description: Allows the map to render a slideshow.
        default: false
    imgmap.cmd.restoremap:
        description: Allows the map to be restored to it's original state.
        default: false
    imgmap.cmd.imgmap:
        description: Allows the user to access the version.
        default: false