name: ImgMap
version: 3
main: com.tenko.ImgMap

commands:
    map:
        description: Renders an image on the map the commander is holding.
        usage: /map <url>
    images:
        description: Lists all currently local images under /images/.
        usage: /images
    smap:
        description: Renders a slideshow on the current map.
        usage: /smap <waitTimeBetweenImages> <url1> [url...]
    restoremap:
        description: Removes all renderers on a map and makes it into a vanilla map.
        usage: /restoremap
        aliases: rmap
    imgmap:
        description: Returns plugin information.
        usage: /imgmap
        aliases: imap
    ani:
        description: Renders animated gif on map.
        usage: /ani <url>